### ISSUE TITLE
Setting gamemode fails

### ISSUE THREAD

**Issue by Knight1** [Snowiiii/Pumpkin#158]
**Describe the bug**
Setting gamemode fails

**To Reproduce**
I used this pregenerated 1.21.1 Map
https://www.minecraftmaps.com/50459-shadow-of-the-skeleton-king

Setting gamemode to creative crashes the Process.

**Expected behavior**
Gamemode set to creative or an error.

**Environment (please complete the following information):**

- Operating System: [Ubuntu 20.04.6 LTS, amd64]
- Server Software Version/Commit: [master branch, 78d606978633379792ac399acb6e724da054b88c]
- rustc 1.82.0 (f6e511eec 2024-10-15)`

**Additional context**
Happens ingame and in the CLI without any User online.

```
➜  Pumpkin git:(master) ✗ RUST_BACKTRACE=full ./target/debug/pumpkin
2024-10-20T01:24:28.084Z INFO  [pumpkin::server@main] Loading Plugins
2024-10-20T01:24:28.505Z INFO  [pumpkin::server::connection_cache@main] Loading server favicon from 'icon.png'
2024-10-20T01:24:28.506Z WARN  [pumpkin::server::connection_cache@main] Failed to load icon from 'icon.png': No such file or directory (os error 2)
2024-10-20T01:24:28.506Z INFO  [pumpkin@main] Started Server took 423ms
2024-10-20T01:24:28.506Z INFO  [pumpkin@main] You now can connect to the server, Listening on 0.0.0.0:25565
gamemode creative knight22
thread 'tokio-runtime-worker' panicked at pumpkin/src/world/mod.rs:321:44:
Cannot block the current thread from within a runtime. This happens because a function attempted to block the current thread while the thread is being used to drive asynchronous tasks.
stack backtrace:
   0:     0x7fd1ab0adcca - std::backtrace_rs::backtrace::libunwind::trace::h99efb0985cae5d78
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7fd1ab0adcca - std::backtrace_rs::backtrace::trace_unsynchronized::he2c1aa63b3f7fad8
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fd1ab0adcca - std::sys::backtrace::_print_fmt::h8a221d40f5e0f88b
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:66:9
   3:     0x7fd1ab0adcca - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:39:26
   4:     0x7fd1ab0d570b - core::fmt::rt::Argument::fmt::h5da9c218ec984eaf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/rt.rs:177:76
   5:     0x7fd1ab0d570b - core::fmt::write::hf5713710ce10ff22
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/mod.rs:1178:21
   6:     0x7fd1ab0aa403 - std::io::Write::write_fmt::hda708db57927dacf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/io/mod.rs:1823:15
   7:     0x7fd1ab0af332 - std::sys::backtrace::BacktraceLock::print::hbcdbec4d97c91528
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:42:9
   8:     0x7fd1ab0af332 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:266:22
   9:     0x7fd1ab0aef9e - std::panicking::default_hook::h81c8cd2e7c59ee33
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:293:9
  10:     0x7fd1aa4d6753 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4ec72cb8441b5465
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/boxed.rs:2245:9
  11:     0x7fd1aa5e0933 - pumpkin::main::{{closure}}::{{closure}}::h87ff9fd493bacd09
                               at /home/knight/code/Pumpkin/pumpkin/src/main.rs:110:9
  12:     0x7fd1ab0afbf2 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h375ef7f99b271d16
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/boxed.rs:2245:9
  13:     0x7fd1ab0afbf2 - std::panicking::rust_panic_with_hook::had2118629c312a4a
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:805:13
  14:     0x7fd1ab0af8a7 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:671:13
  15:     0x7fd1ab0ae1a9 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:170:18
  16:     0x7fd1ab0af534 - rust_begin_unwind
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
  17:     0x7fd1aa4cfea3 - core::panicking::panic_fmt::h3eea515d05f7a35e
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
  18:     0x7fd1aa4cfe6b - core::panicking::panic_display::h43c6507275b9b865
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:264:5
  19:     0x7fd1aa4cfe6b - core::option::expect_failed::h6d726c0eb3b486db
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:2025:5
  20:     0x7fd1aae6abed - core::option::Option<T>::expect::h6eb8af21c6576d5d
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/option.rs:928:21
  21:     0x7fd1aa512651 - tokio::future::block_on::block_on::hb9217dbe7b7f2ad8
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/future/block_on.rs:6:21
  22:     0x7fd1aa63a231 - tokio::sync::mutex::Mutex<T>::blocking_lock::h9b4ca35b4da62cff
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/sync/mutex.rs:519:9
  23:     0x7fd1aa553831 - pumpkin::world::World::get_player_by_name::h0f6661ef07450ed4
                               at /home/knight/code/Pumpkin/pumpkin/src/world/mod.rs:321:23
  24:     0x7fd1aa662dca - pumpkin::commands::arg_player::consume_arg_player::hb3f076ec73f39cb9
                               at /home/knight/code/Pumpkin/pumpkin/src/commands/arg_player.rs:30:24
  25:     0x7fd1aa5fb761 - pumpkin::commands::dispatcher::CommandDispatcher::try_is_fitting_path::h51f2ab47528137f9
                               at /home/knight/code/Pumpkin/pumpkin/src/commands/dispatcher.rs:121:28
  26:     0x7fd1aa5fabdc - pumpkin::commands::dispatcher::CommandDispatcher::dispatch::hee4a4cc32d0fb921
                               at /home/knight/code/Pumpkin/pumpkin/src/commands/dispatcher.rs:55:19
  27:     0x7fd1aa644795 - pumpkin::commands::dispatcher::CommandDispatcher::handle_command::{{closure}}::h5f53ade8bf993659
                               at /home/knight/code/Pumpkin/pumpkin/src/commands/dispatcher.rs:30:27
  28:     0x7fd1aa5e0a9c - pumpkin::main::{{closure}}::{{closure}}::h7a8128fc29ab3cef
                               at /home/knight/code/Pumpkin/pumpkin/src/main.rs:146:26
  29:     0x7fd1aa672c2f - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::hb020bbb9bf922d7e
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/core.rs:331:17
  30:     0x7fd1aa67153d - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::ha9182ae2cf2cf9fd
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/loom/std/unsafe_cell.rs:16:9
  31:     0x7fd1aa67153d - tokio::runtime::task::core::Core<T,S>::poll::hda6bb758cf22a0db
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/core.rs:320:13
  32:     0x7fd1aa5c040a - tokio::runtime::task::harness::poll_future::{{closure}}::heef9c8b2245c0e0b
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/harness.rs:500:19
  33:     0x7fd1aa5adb00 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h3f2ab5cb7eb189f2
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panic/unwind_safe.rs:272:9
  34:     0x7fd1aa5cf168 - std::panicking::try::do_call::ha4a022a22229b628
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  35:     0x7fd1aa4dca6b - __rust_try
  36:     0x7fd1aa4dc7a6 - std::panicking::try::h5f3cdb489fcec8d3
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  37:     0x7fd1aa4dc7a6 - std::panic::catch_unwind::hf67ff6a12cfeb80e
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  38:     0x7fd1aa5bbf8f - tokio::runtime::task::harness::poll_future::h586f6af59a4ff67b
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/harness.rs:488:18
  39:     0x7fd1aa5c2167 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hc0c4f3eb5bfe285c
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/harness.rs:209:27
  40:     0x7fd1aa5c5e23 - tokio::runtime::task::harness::Harness<T,S>::poll::h01938d096e06216e
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/harness.rs:154:15
  41:     0x7fd1aa56027b - tokio::runtime::task::raw::poll::h58249d414b83e58f
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/raw.rs:271:5
  42:     0x7fd1aaf8ade7 - tokio::runtime::task::raw::RawTask::poll::hec6983e41757084e
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/raw.rs:201:18
  43:     0x7fd1aaf8f9b2 - tokio::runtime::task::LocalNotified<S>::run::habfc1e5e5fe6093b
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/mod.rs:436:9
  44:     0x7fd1aaf97ead - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::h4e9a496c82fdd0aa
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/worker.rs:598:13
  45:     0x7fd1aaf97d04 - tokio::runtime::coop::with_budget::had9b4d317dd5a546
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5
  46:     0x7fd1aaf97d04 - tokio::runtime::coop::budget::hdb258f1c6515559c
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5
  47:     0x7fd1aaf97d04 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h9856ea46ce020fc6
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/worker.rs:597:9
  48:     0x7fd1aaf973d3 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h4a58f2d3b5b4118d
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/worker.rs:548:24
  49:     0x7fd1aaf97039 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}::h8d9e6a18493912c7
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/worker.rs:513:21
  50:     0x7fd1aaf61c10 - tokio::runtime::context::scoped::Scoped<T>::set::hd74ec1c38cf0894f
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/scoped.rs:40:9
  51:     0x7fd1aaf73ceb - tokio::runtime::context::set_scheduler::{{closure}}::h23c15be5e3f879f7
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:26
  52:     0x7fd1aaf4df80 - std::thread::local::LocalKey<T>::try_with::h49cd1446d547dbe4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:283:12
  53:     0x7fd1aaf4d71b - std::thread::local::LocalKey<T>::with::h100574f80ca0eee7
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:260:9
  54:     0x7fd1aaf73c74 - tokio::runtime::context::set_scheduler::h89e952c2b51c82f5
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:9
  55:     0x7fd1aaf96f44 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::hac99465ae77a49f2
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/worker.rs:508:9
  56:     0x7fd1aaf5aa70 - tokio::runtime::context::runtime::enter_runtime::h95ba606a2f3f7365
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
  57:     0x7fd1aaf96ce6 - tokio::runtime::scheduler::multi_thread::worker::run::h84e4553eb9df6659
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/worker.rs:500:5
  58:     0x7fd1aaf96a0b - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}::h8735acc465766a11
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/worker.rs:466:45
  59:     0x7fd1aaf5afde - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::haeb56e1cd66d62bd
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/blocking/task.rs:42:21
  60:     0x7fd1aaf82813 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h967eb4f1edf53d90
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/core.rs:331:17
  61:     0x7fd1aaf82621 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hf2da35c082f13468
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/loom/std/unsafe_cell.rs:16:9
  62:     0x7fd1aaf82621 - tokio::runtime::task::core::Core<T,S>::poll::ha6e84bd8a628ae40
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/core.rs:320:13
  63:     0x7fd1aaf871fe - tokio::runtime::task::harness::poll_future::{{closure}}::hf7e9f43c3555ad29
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/harness.rs:500:19
  64:     0x7fd1aaf4c941 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h599e7f5b6f28b1ee
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panic/unwind_safe.rs:272:9
  65:     0x7fd1aaf93819 - std::panicking::try::do_call::h8b8eab38e4f4d5db
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  66:     0x7fd1aaf3bb5b - __rust_try
  67:     0x7fd1aaf39636 - std::panicking::try::h0dd31790a24fba6c
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  68:     0x7fd1aaf39636 - std::panic::catch_unwind::he2e204f91a5384f8
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  69:     0x7fd1aaf86cb0 - tokio::runtime::task::harness::poll_future::h19453bdbeec66a83
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/harness.rs:488:18
  70:     0x7fd1aaf85bde - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hfdcb7e4ebbd91bcd
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/harness.rs:209:27
  71:     0x7fd1aaf85987 - tokio::runtime::task::harness::Harness<T,S>::poll::hfd423451fadd503c
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/harness.rs:154:15
  72:     0x7fd1aaf8b07d - tokio::runtime::task::raw::poll::h4bab95b8434effd5
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/raw.rs:271:5
  73:     0x7fd1aaf8ade7 - tokio::runtime::task::raw::RawTask::poll::hec6983e41757084e
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/raw.rs:201:18
  74:     0x7fd1aaf8fa77 - tokio::runtime::task::UnownedTask<S>::run::hddfa774f4f2a4b01
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/task/mod.rs:473:9
  75:     0x7fd1aaf8fdc7 - tokio::runtime::blocking::pool::Task::run::h8585ed43d256f467
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/blocking/pool.rs:160:9
  76:     0x7fd1aaf92323 - tokio::runtime::blocking::pool::Inner::run::h9d66a0e868a84cba
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/blocking/pool.rs:518:17
  77:     0x7fd1aaf92024 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h6712f615cd51c70d
                               at /home/knight/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/blocking/pool.rs:476:13
  78:     0x7fd1aaf4d4f6 - std::sys::backtrace::__rust_begin_short_backtrace::he97b79739878cc34
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:154:18
  79:     0x7fd1aaf508f2 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hbd70afaaeabed140
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/mod.rs:522:17
  80:     0x7fd1aaf4c9e2 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc23fd76874a77afe
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panic/unwind_safe.rs:272:9
  81:     0x7fd1aaf93753 - std::panicking::try::do_call::h5d9d46cb4512e3e4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
  82:     0x7fd1aaf53eab - __rust_try
  83:     0x7fd1aaf50537 - std::panicking::try::ha5c6a0a27d926edf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
  84:     0x7fd1aaf50537 - std::panic::catch_unwind::h9b4c58c2c4a809b1
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
  85:     0x7fd1aaf50537 - std::thread::Builder::spawn_unchecked_::{{closure}}::ha39e07d2aa3dbee9
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/mod.rs:521:30
  86:     0x7fd1aaf2f89f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdb96a7038e3010cd
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
  87:     0x7fd1ab0b1ecb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd6eefa32c9acf934
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/boxed.rs:2231:9
  88:     0x7fd1ab0b1ecb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6bca3a1f077b8c81
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/boxed.rs:2231:9
  89:     0x7fd1ab0b1ecb - std::sys::pal::unix::thread::Thread::new::thread_start::hcdbd1049068002f4
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/pal/unix/thread.rs:105:17
  90:     0x7fd1aa355609 - start_thread
  91:     0x7fd1aa10f353 - clone
  92:                0x0 - <unknown>
```

**Comment by Snowiiii** [comment]
Hey, This is due to the tokio rewrite from yesterday. I will try to fix Commands as soon as possible

**Comment by Snowiiii** [comment]
Hey @Knight1 Commands do work now, https://github.com/Snowiiii/Pumpkin/commit/3d0e42315e394d477549b304f61c4d8a0b2f2440, https://github.com/Snowiiii/Pumpkin/commit/7347bae275e65351ced7f80098e98aab48889aa4. But currently Target selection does not work. So you can't select other Player. Should be also fixed soon

**Comment by Snowiiii** [comment]
Great https://github.com/Snowiiii/Pumpkin/commit/29b3c8260b7d3cd1c4251f6878f45a9ceae23640 just fixed Target selection. Everything works again like normal.
