### ISSUE TITLE
Network Protocol Error on multiple connections

### ISSUE THREAD

**Issue by Commandcracker** [Snowiiii/Pumpkin#368]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Windows

### Server Software Version/Commit

0.1.0-dev e26ffae-m

### What happened?

![Screenshot 2024-12-04 134800](https://github.com/user-attachments/assets/442e2060-f80c-4b30-9c5f-d51b1cfb0d51)

[disconnect-2024-12-04_14.10.28-client.txt](https://github.com/user-attachments/files/18008862/disconnect-2024-12-04_14.10.28-client.txt)

### To Reproduce

Join the public server(pumpkin.kralverde.dev) with 2 different accounts on the same computer/network.

### Expected behavior

You should be able to join a minecraft together with someone on your same network.

**Comment by Yimura** [comment]
Are you using 2 different accounts to perform this action? Client's seem to be distinguished by their UUID's from Pumpkin's source code:
https://github.com/Snowiiii/Pumpkin/blob/e26ffae8430e173a8b05b6b6a457b5a144b04ee2/pumpkin/src/world/mod.rs#L104

Granted the server/client shouldn't outright bork and instead give a proper response on why the connection failed (aka. already connected to this server with the same User Account).

**Comment by Commandcracker** [comment]
Lucas11 on discord said, that it also happens from another random player.

**Comment by Commandcracker** [comment]
Error with mappings:
```
[19:38:20] [Render thread/INFO] (Minecraft) [System] [CHAT] Commandcracker joined the game.
[19:38:21] [Render thread/ERROR] (Minecraft) Failed to recreate fishing hook on client. null (id: 0) is not a valid owner.
[19:38:21] [Render thread/ERROR] (Minecraft) Failed to handle packet EntityTrackerUpdateS2CPacket[id=8, packedItems=[SerializedEntry[id=17, serializer=net.minecraft.entity.data.TrackedDataHandler$$Lambda/0x0000029a578bc2e0@5eac24de, value=127]]], disconnecting
 java.lang.ArrayIndexOutOfBoundsException: Index 17 out of bounds for length 10
	at knot/net.minecraft.entity.data.DataTracker.writeUpdatedEntries(DataTracker.java:116) ~[minecraft-common-9b4b3229ca-1.21.4-net.fabricmc.yarn.1_21_4.1.21.4+build.1-v2.jar:?]
	at knot/net.minecraft.client.network.ClientPlayNetworkHandler.onEntityTrackerUpdate(ClientPlayNetworkHandler.java:587) ~[minecraft-clientOnly-9b4b3229ca-1.21.4-net.fabricmc.yarn.1_21_4.1.21.4+build.1-v2.jar:?]
	at knot/net.minecraft.network.packet.s2c.play.EntityTrackerUpdateS2CPacket.apply(EntityTrackerUpdateS2CPacket.java:54) ~[minecraft-common-9b4b3229ca-1.21.4-net.fabricmc.yarn.1_21_4.1.21.4+build.1-v2.jar:?]
	at knot/net.minecraft.network.packet.s2c.play.EntityTrackerUpdateS2CPacket.apply(EntityTrackerUpdateS2CPacket.java:12) ~[minecraft-common-9b4b3229ca-1.21.4-net.fabricmc.yarn.1_21_4.1.21.4+build.1-v2.jar:?]
	at knot/net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:27) ~[minecraft-common-9b4b3229ca-1.21.4-net.fabricmc.yarn.1_21_4.1.21.4+build.1-v2.jar:?]
	at knot/net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:164) [minecraft-common-9b4b3229ca-1.21.4-net.fabricmc.yarn.1_21_4.1.21.4+build.1-v2.jar:?]
	at knot/net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [minecraft-common-9b4b3229ca-1.21.4-net.fabricmc.yarn.1_21_4.1.21.4+build.1-v2.jar:?]
	at knot/net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:138) [minecraft-common-9b4b3229ca-1.21.4-net.fabricmc.yarn.1_21_4.1.21.4+build.1-v2.jar:?]
	at knot/net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:123) [minecraft-common-9b4b3229ca-1.21.4-net.fabricmc.yarn.1_21_4.1.21.4+build.1-v2.jar:?]
	at knot/net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1296) [minecraft-clientOnly-9b4b3229ca-1.21.4-net.fabricmc.yarn.1_21_4.1.21.4+build.1-v2.jar:?]
	at knot/net.minecraft.client.MinecraftClient.run(MinecraftClient.java:922) [minecraft-clientOnly-9b4b3229ca-1.21.4-net.fabricmc.yarn.1_21_4.1.21.4+build.1-v2.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:267) [minecraft-clientOnly-9b4b3229ca-1.21.4-net.fabricmc.yarn.1_21_4.1.21.4+build.1-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
[19:38:21] [Render thread/WARN] (Minecraft) Client disconnected with reason: Network Protocol Error
```

**Comment by lucas11222** [comment]
ok so is returning null and that is the error
